spring:
  application:
    name: integration
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_URI}
            secret-keys:
              - api-key-2
              - api-key-3
            credential:
              managed-identity-enabled: true
              client-id: ${USER_MANAGED_IDENTITY_CLIENT}
          property-sources[1]:
            endpoint: ${AZURE_KEY_VAULT_2_URI}
            secret-keys:
              - api-key-4
              - api-key-5
            credential:
              managed-identity-enabled: true
              client-id: ${USER_MANAGED_IDENTITY_CLIENT}
local:
  timeout: 3000
logging:
  level:
    com.azure: DEBUG
api-key-2: af