application:
  name: integration-test
cloud:
  azure:
    keyvault:
      secret:
        property-sources: [] # Deshabilitamos la configuración de KeyVault para pruebas

local:
  timeout: 3000
api-key-2: hola
api-key-3: hola